/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStockTransferRouteImport } from './routes/_authenticated/stock-transfer'
import { Route as AuthenticatedStockItemsRouteImport } from './routes/_authenticated/stock-items'
import { Route as AuthenticatedStockRouteImport } from './routes/_authenticated/stock'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDeliveryReportRouteImport } from './routes/_authenticated/delivery-report'
import { Route as AuthenticatedDeliveryExpensesRouteImport } from './routes/_authenticated/delivery-expenses'
import { Route as AuthenticatedDailyClosingRouteImport } from './routes/_authenticated/daily-closing'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCategoriesRouteImport } from './routes/_authenticated/categories'
import { Route as AuthenticatedCashMovementsRouteImport } from './routes/_authenticated/cash-movements'
import { Route as ApiPublicWhatsappInvoiceRouteImport } from './routes/api/public/whatsapp-invoice'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockTransferRoute =
  AuthenticatedStockTransferRouteImport.update({
    id: '/stock-transfer',
    path: '/stock-transfer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockItemsRoute = AuthenticatedStockItemsRouteImport.update({
  id: '/stock-items',
  path: '/stock-items',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockRoute = AuthenticatedStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryReportRoute =
  AuthenticatedDeliveryReportRouteImport.update({
    id: '/delivery-report',
    path: '/delivery-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryExpensesRoute =
  AuthenticatedDeliveryExpensesRouteImport.update({
    id: '/delivery-expenses',
    path: '/delivery-expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDailyClosingRoute =
  AuthenticatedDailyClosingRouteImport.update({
    id: '/daily-closing',
    path: '/daily-closing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesRoute = AuthenticatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCashMovementsRoute =
  AuthenticatedCashMovementsRouteImport.update({
    id: '/cash-movements',
    path: '/cash-movements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhatsappInvoiceRoute =
  ApiPublicWhatsappInvoiceRouteImport.update({
    id: '/api/public/whatsapp-invoice',
    path: '/api/public/whatsapp-invoice',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/cash-movements': typeof AuthenticatedCashMovementsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/delivery-expenses': typeof AuthenticatedDeliveryExpensesRoute
  '/delivery-report': typeof AuthenticatedDeliveryReportRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stock-items': typeof AuthenticatedStockItemsRoute
  '/stock-transfer': typeof AuthenticatedStockTransferRoute
  '/api/public/whatsapp-invoice': typeof ApiPublicWhatsappInvoiceRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/cash-movements': typeof AuthenticatedCashMovementsRoute
  '/categories': typeof AuthenticatedCategoriesRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/delivery-expenses': typeof AuthenticatedDeliveryExpensesRoute
  '/delivery-report': typeof AuthenticatedDeliveryReportRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/pos': typeof AuthenticatedPosRoute
  '/production': typeof AuthenticatedProductionRoute
  '/products': typeof AuthenticatedProductsRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stock': typeof AuthenticatedStockRoute
  '/stock-items': typeof AuthenticatedStockItemsRoute
  '/stock-transfer': typeof AuthenticatedStockTransferRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/whatsapp-invoice': typeof ApiPublicWhatsappInvoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cash-movements': typeof AuthenticatedCashMovementsRoute
  '/_authenticated/categories': typeof AuthenticatedCategoriesRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/daily-closing': typeof AuthenticatedDailyClosingRoute
  '/_authenticated/delivery-expenses': typeof AuthenticatedDeliveryExpensesRoute
  '/_authenticated/delivery-report': typeof AuthenticatedDeliveryReportRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stock': typeof AuthenticatedStockRoute
  '/_authenticated/stock-items': typeof AuthenticatedStockItemsRoute
  '/_authenticated/stock-transfer': typeof AuthenticatedStockTransferRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/whatsapp-invoice': typeof ApiPublicWhatsappInvoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cash-movements'
    | '/categories'
    | '/customers'
    | '/daily-closing'
    | '/delivery-expenses'
    | '/delivery-report'
    | '/expenses'
    | '/pos'
    | '/production'
    | '/products'
    | '/purchases'
    | '/recipes'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/stock-items'
    | '/stock-transfer'
    | '/api/public/whatsapp-invoice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/cash-movements'
    | '/categories'
    | '/customers'
    | '/daily-closing'
    | '/delivery-expenses'
    | '/delivery-report'
    | '/expenses'
    | '/pos'
    | '/production'
    | '/products'
    | '/purchases'
    | '/recipes'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock'
    | '/stock-items'
    | '/stock-transfer'
    | '/'
    | '/api/public/whatsapp-invoice'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cash-movements'
    | '/_authenticated/categories'
    | '/_authenticated/customers'
    | '/_authenticated/daily-closing'
    | '/_authenticated/delivery-expenses'
    | '/_authenticated/delivery-report'
    | '/_authenticated/expenses'
    | '/_authenticated/pos'
    | '/_authenticated/production'
    | '/_authenticated/products'
    | '/_authenticated/purchases'
    | '/_authenticated/recipes'
    | '/_authenticated/reports'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/stock'
    | '/_authenticated/stock-items'
    | '/_authenticated/stock-transfer'
    | '/_authenticated/'
    | '/api/public/whatsapp-invoice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicWhatsappInvoiceRoute: typeof ApiPublicWhatsappInvoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-transfer': {
      id: '/_authenticated/stock-transfer'
      path: '/stock-transfer'
      fullPath: '/stock-transfer'
      preLoaderRoute: typeof AuthenticatedStockTransferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-items': {
      id: '/_authenticated/stock-items'
      path: '/stock-items'
      fullPath: '/stock-items'
      preLoaderRoute: typeof AuthenticatedStockItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock': {
      id: '/_authenticated/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof AuthenticatedStockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-report': {
      id: '/_authenticated/delivery-report'
      path: '/delivery-report'
      fullPath: '/delivery-report'
      preLoaderRoute: typeof AuthenticatedDeliveryReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-expenses': {
      id: '/_authenticated/delivery-expenses'
      path: '/delivery-expenses'
      fullPath: '/delivery-expenses'
      preLoaderRoute: typeof AuthenticatedDeliveryExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-closing': {
      id: '/_authenticated/daily-closing'
      path: '/daily-closing'
      fullPath: '/daily-closing'
      preLoaderRoute: typeof AuthenticatedDailyClosingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories': {
      id: '/_authenticated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthenticatedCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cash-movements': {
      id: '/_authenticated/cash-movements'
      path: '/cash-movements'
      fullPath: '/cash-movements'
      preLoaderRoute: typeof AuthenticatedCashMovementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp-invoice': {
      id: '/api/public/whatsapp-invoice'
      path: '/api/public/whatsapp-invoice'
      fullPath: '/api/public/whatsapp-invoice'
      preLoaderRoute: typeof ApiPublicWhatsappInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCashMovementsRoute: typeof AuthenticatedCashMovementsRoute
  AuthenticatedCategoriesRoute: typeof AuthenticatedCategoriesRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDailyClosingRoute: typeof AuthenticatedDailyClosingRoute
  AuthenticatedDeliveryExpensesRoute: typeof AuthenticatedDeliveryExpensesRoute
  AuthenticatedDeliveryReportRoute: typeof AuthenticatedDeliveryReportRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStockRoute: typeof AuthenticatedStockRoute
  AuthenticatedStockItemsRoute: typeof AuthenticatedStockItemsRoute
  AuthenticatedStockTransferRoute: typeof AuthenticatedStockTransferRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCashMovementsRoute: AuthenticatedCashMovementsRoute,
  AuthenticatedCategoriesRoute: AuthenticatedCategoriesRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDailyClosingRoute: AuthenticatedDailyClosingRoute,
  AuthenticatedDeliveryExpensesRoute: AuthenticatedDeliveryExpensesRoute,
  AuthenticatedDeliveryReportRoute: AuthenticatedDeliveryReportRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStockRoute: AuthenticatedStockRoute,
  AuthenticatedStockItemsRoute: AuthenticatedStockItemsRoute,
  AuthenticatedStockTransferRoute: AuthenticatedStockTransferRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicWhatsappInvoiceRoute: ApiPublicWhatsappInvoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
